### ISSUE TITLE
[BUG] JsonWriter puts metadata as a child of 'shapes' but it should be top-level

### ISSUE THREAD

**Issue by stevelr** [johnstonskj/rust-atelier#34]
Per the [JSON-AST specification](https://awslabs.github.io/smithy/1.0/spec/core/json-ast.html#top-level-properties), the merged "metadata" is supposed to be a top-level property of the json ast model, at the same level as "shapes", but JsonWriter puts it underneath "shapes" here:
https://github.com/johnstonskj/rust-atelier/blob/293e8244dbff9dc550116485e5850f502e2e367a/atelier-json/src/writer.rs#L111

**Comment by johnstonskj** [comment]
Fixed in https://github.com/johnstonskj/rust-atelier/commit/6bdce1062e652660c438cfba7638470db33978c0 to release as 0.2.7
