### ISSUE TITLE
[BUG] Bad cert for rust-atelier.dev

### ISSUE THREAD

**Issue by brendo-m** [johnstonskj/rust-atelier#42]
**Describe the bug**
`SSL_ERROR_BAD_CERT_DOMAIN` when accessing https://rust-atelier.dev/

**Comment by johnstonskj** [comment]
Thanks, I’ll look into the GitHub config

**Comment by johnstonskj** [comment]
Made changes to Pages settings (not sure why it keeps forgetting these). Will take a while to replicate.

**Comment by johnstonskj** [comment]
Appears to be working again.
